.TH GRUB-OFPATHNAME 3 "Wed Feb 26 2014"
.SH NAME
\fBgrub-ofpathname\fR \(em Generate an IEEE-1275 device path for a specified device.

.SH SYNOPSIS
\fBgrub-ofpathname\fR \fIDEVICE\fR

.SH DESCRIPTION
\fBgrub-ofpathname\fR generates an IEEE-1275 device path for the specified \fIDEVICE\fR.

.SH SEE ALSO
.BR "info grub"
