.TH GRUB-SETPASSWORD 3 "Thu Jun 25 2015"
.SH NAME
\fBgrub-setpassword\fR \(em Generate the user.cfg file containing the hashed grub bootloader password.

.SH SYNOPSIS
\fBgrub-setpassword\fR [OPTION]

.SH DESCRIPTION
\fBgrub-setpassword\fR outputs the user.cfg file which contains the hashed GRUB bootloader password. This utility only supports configurations where there is a single root user.

The file has the format:
GRUB2_PASSWORD=<\fIhashed password\fR>.

.SH OPTIONS
.TP
-h, --help
Display program usage and exit.
.TP
-v, --version
Display the current version.
.TP
-o, --output[=\fIDIRECTORY PATH\fR]
Choose the file path to which user.cfg will be written.

.SH SEE ALSO
.BR "info grub"

.BR "info grub2-mkpasswd-pbkdf2"
