.TH GRUB-MKRELPATH 3 "Wed Feb 26 2014"
.SH NAME
\fBgrub-mkrelpath\fR \(em Generate a relative GRUB path given an OS path.

.SH SYNOPSIS
\fBgrub-mkrelpath\fR \fIFILE\fR

.SH DESCRIPTION
\fBgrub-mkrelpath\fR takes an OS filesystem path for \fIFILE\fR and returns a relative path suitable for use in a GRUB configuration file.

.SH SEE ALSO
.BR "info grub"
