.TH GRUB-MENULST2CFG 1 "Wed Feb 26 2014"
.SH NAME
\fBgrub-menulst2cfg\fR \(em Convert a configuration file from GRUB 0.xx to GRUB 2.xx format.

.SH SYNOPSIS
\fBgrub-menulst2cfg\fR [\fIINFILE\fR [\fIOUTFILE\fR]]

.SH DESCRIPTION
\fBgrub-menulst2cfg\fR converts a configuration file from GRUB 0.xx to the current format.

.SH SEE ALSO
.BR "info grub"
