.TH GRUB-SET-BOOTFLAG 1 "Tue Jun 12 2018"
.SH NAME
\fBgrub-set-bootflag\fR \(em Set a bootflag in the GRUB environment block.

.SH SYNOPSIS
\fBgrub-set-bootflag\fR <\fIBOOTFLAG\fR>

.SH DESCRIPTION
\fBgrub-set-bootflag\fR is a command line to set bootflags in GRUB's
stored environment.

.SH COMMANDS
.TP
\fBBOOTFLAG\fR
.RS 7
Bootflag to set, one of \fIboot_success\fR or \fIshow_menu_once\fR.
.RE

.SH SEE ALSO
.BR "info grub"
