.TH GRUB-SPARC64-SETUP 3 "Wed Feb 26 2014"
.SH NAME
\fBgrub-sparc64-setup\fR \(em Set up a device to boot a sparc64 GRUB image.

.SH SYNOPSIS
\fBgrub-sparc64-setup\fR [OPTIONS].

.SH DESCRIPTION
You should not normally run this program directly.  Use grub-install instead.

.SH SEE ALSO
.BR "info grub"
