.TH GRUB-SCRIPT-CHECK 3 "Wed Feb 26 2014"
.SH NAME
\fBgrub-script-check\fR \(em Check GRUB configuration file for syntax errors.

.SH SYNOPSIS
\fBgrub-script-check\fR [-v | --verbose] \fIPATH\fR

.SH DESCRIPTION
\fBgrub-script-check\fR verifies that a specified GRUB configuration file does not contain syntax errors.

.SH OPTIONS
.TP
--verbose
Print verbose output.

.TP
\fIPATH\fR
Path of the file to use as input.

.SH SEE ALSO
.BR "info grub"
