.TH GRUB-MKCONFIG 1 "Wed Feb 26 2014"
.SH NAME
\fBgrub-mkconfig\fR \(em Generate a GRUB configuration file.

.SH SYNOPSIS
\fBgrub-mkconfig\fR [-o | --output=\fIFILE\fR]

.SH DESCRIPTION
\fBgrub-mkconfig\fR generates a configuration file for GRUB.

.SH OPTIONS
.TP
\fB--output\fR=\fIFILE\fR
Write generated output to \fIFILE\fR.

.TP
\fB--no-grubenv-update\fR
Do not update variables in the grubenv file.

.SH SEE ALSO
.BR "info grub"
