.TH GRUB-MACBLESS 1 "Wed Feb 26 2014"
.SH NAME
\fBgrub-macbless\fR \(em Mac-style bless on HFS or HFS+

.SH SYNOPSIS
\fBgrub-macbless\fR [-v | --verbose] [-p | --ppc] \fIFILE\fR | [-x | --x86] \fIFILE\fR

.SH OPTIONS
.TP
--x86
Bless for x86 based Macs.

.TP
--ppc
Bless for PPC based Macs.

.TP
--verbose
Print verbose messages.

.SH SEE ALSO
.BR "info grub"
