/*
 *  GRUB  --  GRand Unified Bootloader
 *  Copyright (C) 2024 Free Software Foundation, Inc.
 *
 *  GRUB is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  GRUB is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with GRUB.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 *  This file is generated by 'asn1Parser tpm2key.asn' and the '#include'
 *  headers are replaced with the ones in grub2.
 *  - 'grub/mm.h' for the definition of 'NULL'
 *  - 'libtasn1.h' for the definition of 'asn1_static_node'
 */

#include <grub/mm.h>
#include <libtasn1.h>

const asn1_static_node tpm2key_asn1_tab[] = {
  { "TPM2KEY", 536875024, NULL },
  { NULL, 1073741836, NULL },
  { "TPMPolicy", 1610612741, NULL },
  { "CommandCode", 1610620931, NULL },
  { NULL, 2056, "0"},
  { "CommandPolicy", 536879111, NULL },
  { NULL, 2056, "1"},
  { "TPMAuthPolicy", 1610612741, NULL },
  { "Name", 1610637346, NULL },
  { NULL, 2056, "0"},
  { "Policy", 536879115, NULL },
  { NULL, 1073743880, "1"},
  { NULL, 2, "TPMPolicy"},
  { "TPMKey", 536870917, NULL },
  { "type", 1073741836, NULL },
  { "emptyAuth", 1610637316, NULL },
  { NULL, 2056, "0"},
  { "policy", 1610637323, NULL },
  { NULL, 1073743880, "1"},
  { NULL, 2, "TPMPolicy"},
  { "secret", 1610637319, NULL },
  { NULL, 2056, "2"},
  { "authPolicy", 1610637323, NULL },
  { NULL, 1073743880, "3"},
  { NULL, 2, "TPMAuthPolicy"},
  { "description", 1610637346, NULL },
  { NULL, 2056, "4"},
  { "rsaParent", 1610637316, NULL },
  { NULL, 2056, "5"},
  { "parent", 1073741827, NULL },
  { "pubkey", 1073741831, NULL },
  { "privkey", 7, NULL },
  { NULL, 0, NULL }
};
